coverage:
  status:
    project:
      default:
        informational: true # Don't fail CI
# Don't count lines of code in these directories
ignore:
    - tests
fixes:
  - "ansible_collections/community/digitalocean/::"
