authors:
  - Ansible (https://github.com/ansible)
  - BondAnthony (https://github.com/BondAnthony)
  - Akasurde (https://github.com/Akasurde)
  - pmarques (https://github.com/pmarques)
  - geerlingguy (https://www.jeffgeerling.com/)
  - Andres Hermosilla (https://github.com/rezen)
  - Luis (https://github.com/lalvarezguillen)
  - grzs (https://github.com/grzs)
  - Lucas Basquerotto (https://github.com/lucasbasquerotto)
  - Tadej Borovšak (https://github.com/tadeboro)
  - Mark Mercado (https://github.com/mamercad)
  - Mike Pontillo (https://github.com/mpontillo)
  - Felix Fontein (https://github.com/felixfontein)
  - Andrew Starr-Bochicchio (https://github.com/andrewsomething)
  - Sam Pinkus (https://github.com/sgpinkus)
  - Luis (https://github.com/lalvarezguillen)
  - John R Barker (https://github.com/gundalow)
  - Andrew Klychkov (https://github.com/Andersson007)
  - Tyler Auerbeck (https://github.com/tylerauerbeck)
  - Angel Aviel Domaoan (https://github.com/tenshiAMD)
  - Max Truxa (https://github.com/maxtruxa)
dependencies: {}
description: DigitalOcean Ansible Collection.
documentation: https://docs.ansible.com/ansible/latest/collections/community/digitalocean/
homepage: https://github.com/ansible-collections/community.digitalocean
issues: https://github.com/ansible-collections/community.digitalocean/issues
license_file: COPYING
name: digitalocean
namespace: community
readme: README.md
repository: https://github.com/ansible-collections/community.digitalocean
tags:
  - digitalocean
  - cloud
  - droplet
version: 1.7.0
build_ignore:
  - .DS_Store
  - '*.tar.gz'
