authors:
  - Ansible (https://github.com/ansible)
  - BondAnthony (https://github.com/BondAnthony)
  - Akasurde (https://github.com/Akasurde)
  - pmarques (https://github.com/pmarques)
  - geerlingguy (https://www.jeffgeerling.com/)
dependencies: {}
description: DigitalOcean Ansible Collection.
documentation: ''
homepage: https://github.com/ansible-collections/community.digitalocean
issues: https://github.com/ansible-collections/community.digitalocean/issues
license_file: COPYING
name: digitalocean
namespace: community
readme: README.md
repository: https://github.com/ansible-collections/community.digitalocean
tags:
  - digitalocean
  - cloud
  - droplet
version: 0.1.0
build_ignore:
  - .DS_Store
  - '*.tar.gz'
