---
- name: testing
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: List all available 1-Click Applications
      community.digitalocean.one_click_info:
        oauth_token: "{{ lookup('ansible.builtin.env', 'DO_API_TOKEN') }}"
