---
- name: testing
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: 1-click-app
      community.digitalocean.one_click_info:
        state: present

    - name: 1-click-app
      community.digitalocean.one_click_info:
        state: absent

    # - name: 1-click-app
    #   community.digitalocean.one_click:
    #     state: absent
    #     name: foo
