name: dev-integration-module
description: integration test by module

inputs:
  module:
    description: the module
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "module: ${{ inputs.module }}"
