bugfixes:
  - digital_ocean_kubernetes - module didn't return kubeconfig properly, return documentation was 
    invalid. Fixed version returns data with the same structure all the time, also it is aligned 
    with M(community.digitalocean.digital_ocean_kubernetes_info) documentation return data now.
    (https://github.com/ansible-collections/community.digitalocean/issues/322).