name: integration-module

on:
  workflow_call:
    inputs:
      module:
        required: true
        type: string

# concurrency:
#   group: ci-cloud-integration-tests
#   cancel-in-progress: false

jobs:

  integration:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Perform testing (${{ inputs.module }})
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          target: ${{ inputs.module }}
          ansible-core-version: 2.11
          pre-test-cmd: >-  # Configure integration test run
            DO_API_KEY=${{ secrets.DO_API_KEY }}
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            ./tests/utils/render.sh
            tests/integration/integration_config.yml.template
            > tests/integration/integration_config.yml
          python-version: 3.9
          target-python-version: 3.9
          testing-type: integration
          test-deps: community.general
