name: ansible-test coverage
on:
  # pull_request:
  # push:
  schedule:
    - cron: '0 6 * * *'

jobs:

  integration:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ansible_collections/community/digitalocean

    steps:
      - name: Clone the repo
        uses: actions/checkout@v2
        with:
          path: ansible_collections/community/digitalocean

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Ansible
        run: pip install ansible

      # ansible-test support producing code coverage date
      - name: Generate coverage report
        run: ansible-test coverage xml -v --requirements --group-by command --group-by version
        working-directory: ./ansible_collections/community/digitalocean

      # See the reports at https://codecov.io/gh/GITHUBORG/REPONAME
      - uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: false
