# https://black.readthedocs.io/en/stable/integrations/github_actions.html
name: black

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
