name: dev-integration-module

on:
  workflow_call:
    inputs:
      module:
        required: true
        type: string

jobs:

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: |
          echo "module: ${{ inputs.module }}"
