name: pull-request-integration-ci

on:
  pull_request_target:
    branches: [ ci ]
    types: [ opened, synchronize, reopened ]

concurrency:
  group: cloud-integration-tests
  cancel-in-progress: false

jobs:

  changed-modules:
    # Require reviewers for this environment
    # https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
    environment: integration
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Debug
        run:
          echo "${{ github.event_name }}"

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5
        if: github.event_name == 'pull_request'

      - uses: nrwl/last-successful-commit-action@v1
        id: last_successful_commit_pull_request
        if: github.event_name == 'pull_request'
        with:
          branch: ${{ steps.branch-name.outputs.base_ref_branch }} # Get the last successful commit on master or main branch
          workflow_id: pull-request-integration.yml
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run changed-files with the commit of the last successful test workflow run on main
        if: github.event_name == 'pull_request'
        # id: changed-files-base-sha-pull-request
        id: changed-modules
        uses: tj-actions/changed-files@v22.1
        with:
          base_sha: ${{ steps.last_successful_commit_pull_request.outputs.commit_hash }}
          files: |
            plugins/module_utils/**
            plugins/modules/**

      # - name: Get changed modules
      #   id: changed-modules
      #   uses: tj-actions/changed-files@v22.1
      #   # with:
      #   #   files: |
      #   #     plugins/module_utils/**
      #   #     plugins/modules/**

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-modules.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: Construct module matrix
        id: changed-module-matrix
        run: |
          basenames=()
          for file in ${{ steps.changed-modules.outputs.all_changed_files }}; do
            basenames+=($(basename $file .py))
          done
          printf '::set-output name=matrix::%s\n' $(printf '%s\n' "${basenames[@]}" | jq -R . | jq -sc .)

    outputs:
      changed-files: ${{ steps.changed-modules.outputs.all_changed_files }}
      matrix: ${{ steps.changed-module-matrix.outputs.matrix }}

  integration-test-by-module:
    runs-on: ubuntu-latest
    needs: changed-modules
    strategy:
      matrix:
        module: ${{ fromJson(needs.changed-modules.outputs.matrix) }}
      max-parallel: 1
    steps:

      - name: Perform module_utils or modules testing
        if: ${{ needs.changed-modules.outputs.matrix == '[""]' }}
        run: |
          echo "No module_utils or modules to test"

      - name: Perform module_utils or modules testing
        if: ${{ needs.changed-modules.outputs.matrix != '[""]' }}
        uses: ansible-community/ansible-test-gh-action@unstable/v1
        with:
          ansible-core-version: stable-2.11
          target: ${{ matrix.module }}
          pre-test-cmd: >-  # Configure integration test run
            DO_API_KEY=${{ secrets.DO_API_KEY }}
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            ./tests/utils/render.sh
            tests/integration/integration_config.yml.template
            > tests/integration/integration_config.yml
          python-version: 3.9
          target-python-version: 3.9
          testing-type: integration
          test-deps: community.general
